bot:
  # 机器人QQ号
  qq: 1718018032
  # 老婆的QQ
  wifeQQ: 1718018032
push:
  # 老婆的生日
  birthday: 1990-01-01
  # 恋爱纪念日
  fallingInLove: 1990-01-01
  # 认识的日子
  acquaintance: 1990-01-01
  # 订婚的日子
  engagement: 1990-01-01
  # 领证的日子，自动判断是倒计时还是统计天数
  obtainingACertificate: 1990-01-01


# 获取彩虹屁和天气的接口Key https://www.tianapi.com/
tianxing:
  key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx