name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: scp ssh pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.YUXUAN_MAIN_SERVER_IP }}
        user: ${{ secrets.YUXUAN_MAIN_SERVER_USER }}
        pass: ${{ secrets.YUXUAN_MAIN_SERVER_PASS }}
        scp: |
          ./target/wifePush.jar => /mnt/project/java/wifePush
        last_ssh: |
          echo $LASTSSH 
          cd /mnt/project/java/wifePush
          sh ./shell.sh
    
